package simplegen

const header = `// Code generated by github.com/AlwxSin/simplegen, DO NOT EDIT.
package {{.PackageName}}

{{ if ne (len .Imports) 0 }}
import (
	{{- range $index, $value := .Imports }}
	"{{$value}}"
	{{- end -}}
)
{{end}}

`
